### ISSUE TITLE
Inconsistency in applying denoising in prediction

### ISSUE THREAD

**Issue by annwhoorma** [jianlin-cheng/CryoSegNet#2]
Hi!

I noticed a significant difference between results obtained by using _predict.py_ and _predict_new_data_jpg.py_ if used on the same data. You can see an example below, it's EMPIAR-10345, specifically file _18jam15a_0155_ali_DW_.

This one belong to **test** data.

**Version 1: predict_new_data_jpg.py**

```python
!python CryoSegNet/predict_new_data_jpg.py \
                                --my_dataset_path '/content/test_dataset/10345/images' \
                                --output_path '/content/CryoSegNet/output' \
                                --cryosegnet_checkpoint '/content/pretrained_models/cryosegnet.pth' \
                                --sam_checkpoint '/content/pretrained_models/sam_vit_h_4b8939.pth' \
```

<img src="https://github.com/jianlin-cheng/CryoSegNet/assets/34862867/8e6fad19-82d0-4c69-ae28-056e0e742e83" alt="predicted_18jam15a_0155_ali_DW_result" width="400"/>

Then, I decided to run _predict.py_ script for the same image, and, weirdly, the final result is different from the one from above.

```python
!python CryoSegNet/predict.py \
                                --empiar_id 10345 \
                                --output_path '/content/CryoSegNet/output' \
                                --cryosegnet_checkpoint '/content/pretrained_models/cryosegnet.pth' \
                                --sam_checkpoint '/content/pretrained_models/sam_vit_h_4b8939.pth'
```

![18jam15a_0155_ali_DW_result](https://github.com/jianlin-cheng/CryoSegNet/assets/34862867/819964f0-88ab-4152-97c8-ed65735553a1)

I believe that the reason for this is that _predict.py_ script does not use denoising technique from `utils.denoise.denoise_jpg_image` which is used in _predict_new_data_jpg.py_, since all other parts of the script (excluding plot creation) seem the same.

**Comment by rajangyawali** [comment]
Hello,

Thank you for pointing out this issue. I have changed the code for predict.py 

It should generate the same results.
