### ISSUE TITLE
bbox condition in generate_starfile_new_data_jpg.py

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [jianlin-cheng/CryoSegNet#3]
Hello,

Thank you for an easy-to-understand state-of-the-art implementation for particle picking.

I wanted to understand a snippet from the `generate_starfile_new_data_jpg.py` module:

```
 if len(bboxes) > 1:
            x_ = st.mode([box[2] for box in bboxes["bbox"]])
            y_ = st.mode([box[3] for box in bboxes["bbox"]])
            d_ = np.sqrt((x_ * width / config.input_image_width)**2 + (y_ * height / config.input_image_height)**2)
            r_ = int(d_//2)
            th = r_ * 0.2     

            filename = image_path.split("/")[-1][:-4] + '.mrc'
            for i in range(len(bboxes["bbox"])):
                box, iou = bboxes["bbox"][i], bboxes["iou"][i] 
                if box[2] < x_ + th and box[2] > x_ - th/3 and box[3] < y_ + th and box[3] > y_ - th/3:                 
                    x_new, y_new = int((box[0] + box[2]/2) / config.input_image_width * width) , int((box[1] + box[3]/2) / config.input_image_height * height)
                    star_writer.writerow([filename, x_new, y_new, 2*r_]) 
                    if iou > 0.99:
                        star_writer.writerow([filename, x_new + random.randint(0, int(th/2)), y_new + random.randint(0, int(th/2)), 2*r_])   
                        star_writer.writerow([filename, x_new + random.randint(-int(th/2), 0), y_new + random.randint(-int(th/2), 0), 2*r_])            
                                                                                                                                                                     
        else:
            pass
```

Seems to me that these conditions essentially define a rectangular region that the bounding box must fall within to be considered valid. 
What is this condition checking?

Also, are the boxes in `[x_center, y_center, width, height]` format? 

Thank you!

**Comment by rajangyawali** [comment]
Hi,

These conditions define a bounding circle (not the rectangle) with x-coordinate, y-coordinate and diameter of the circle.

Some conditional checking has been used based on the confidence score given by the model to get the post protein particles. These conditions are used based on multiple experimental trials on the 3D resolution of the density maps.

Further, the x-coordinates and y-coordinates are translated to match the original dimensions of the input image to give x_new and y_new.

Thank you!

**Comment by mansi-aggarwal-2504** [comment]
Right, bounding circle*. Also, are the boxes in [x_center, y_center, width, height] format?

There is also an initial filtering threshold `masks[i]["predicted_iou"] > 0.94` as well. This means that there is another level of conditional checking based on multiple experimental trials on the 3D resolution of the density maps and all of the model's predictions are not sent across?

**Comment by rajangyawali** [comment]
Yes,  you are right. Initially the box is in the format of (x, y, width, height). We then some do postprocessing to filter the proteins with threshold 0.94 and draw a circle with (x, y, diameter) format

**Comment by mansi-aggarwal-2504** [comment]
Thanks for your prompt replies!
I understand the 0.94 threshold but could you explain the intuition behind the next filtration and also the `th = r_ * 0.2` value?

**Comment by rajangyawali** [comment]
The model sometimes output detected aggregated proteins which have larger diameters than the normal proteins and sometimes smaller objects which are not proteins. So to filter out these cases which use this threshold based on multiple trials and experiments. 
For your specific dataset, you may change these thresholds and observe the effects.
