### ISSUE TITLE
Evaluation metrics in the paper

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [jianlin-cheng/CryoSegNet#4]
In reference to [Table 1 in the paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10592924/table/T1/), comparing all the evaluation metrics for the three algorithms, was [evaluation.py](https://github.com/jianlin-cheng/CryoSegNet/blob/main/utils/evaluation.py) used to get CryoSegNet metrics? What is the `threshold` in that module?

The [supplementary table](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10592924/#SD1) in the paper also gives the Topaz particle picking results for different threshold parameters, and ResNet 16 (64 units) was the pre-trained model used for predicton. What were the configuration and evaluation methods for [crYOLO](https://cryolo.readthedocs.io/en/stable/tutorials/tutorial_overview.html#picking)?

**Comment by rajangyawali** [comment]
Yes, evaluation.py is used to evaluate. You can try changing different threshold values and see the results.

Regarding crYOLO, the default pretrained model was used.
